export const REQUEST_FETCH_ORDERS = 'REQUEST_FETCH_ORDERS';

export const RECEIVE_SUCCESS_FETCH_ORDERS = 'RECEIVE_SUCCESS_FETCH_ORDERS';

export const REQUEST_SUBMIT_NEW_ORDER = 'REQUEST_SUBMIT_NEW_ORDER';

export const RECEIVE_SUCCESS_SUBMIT_NEW_ORDER = 'RECEIVE_SUCCESS_SUBMIT_NEW_ORDER';
